"""Curated instruction/offset annotations (L3/L4 + fixed L1/L2/L6 hops).

GENERATED — do not hand-edit the table below. Regenerate with:
    python3 tools/codegen_annotations.py   # (see docs/CALL_LINKAGE_GUIDE.md)

Each entry is analyst judgment (dst_name / resolved_by / confidence) anchored
to a real instruction: ``verify`` asserts every src_offset exists in the decoded
listings (F4b/F4c/F4d) with a matching mnemonic.

TO EXTEND (ต่อยอด): append new dicts to ``EXTRA_ANNOTATIONS`` at the bottom of
this file, or pass ``extra_annotations=[...]`` to ``build.build_from_fragments``.
Required keys: layer, kind, src_module, src_offset, src_name, src_insn,
dst_module, dst_offset, dst_name, resolved_by, confidence, evidence, source.
Optional: note, chain, hop.
"""

from __future__ import annotations

from typing import Any, Dict, List


ANNOTATIONS: List[Dict[str, Any]] = [
    {
        'layer': 'L1',
        'kind': 'invokes_loader',
        'src_module': 'classes.dex',
        'src_offset': '0x2b6c2e',
        'src_name': 'Lcom/snake/App;-><clinit>()V',
        'src_insn': 'invoke-static {...}, Ljava/lang/System;->loadLibrary(Ljava/lang/String;)V',
        'dst_module': 'android-runtime',
        'dst_offset': '',
        'dst_name': 'java.lang.System.loadLibrary("engine")',
        'resolved_by': 'library name from fill-array-data+String([B)',
        'confidence': 'proven',
        'evidence': "fill-array-data instruction at file 0x2b6c22 points to the payload at 0x2b6c38 (ident=0x0300, element_width=1, size=6); the 6 bytes at 0x2b6c40 are 656e67696e65 = 'engine'",
        'source': 'fragments/F2_dex_natives.txt + fragments.json:dex.loader_call_sites',
        'note': '',
        'chain': 'CH-01',
        'hop': 1,
    },
    {
        'layer': 'L1',
        'kind': 'invokes_loader',
        'src_module': 'classes.dex',
        'src_offset': '0x2b6c40',
        'src_name': 'Lcom/snake/App;-><clinit>()V',
        'src_insn': 'fill-array-data payload = 656e67696e65',
        'dst_module': 'classes.dex',
        'dst_offset': '',
        'dst_name': 'string literal "engine" built at run time',
        'resolved_by': 'payload bytes decoded as ASCII',
        'confidence': 'proven',
        'evidence': "fill-array-data instruction at file 0x2b6c22 points to the payload at 0x2b6c38 (ident=0x0300, element_width=1, size=6); the 6 bytes at 0x2b6c40 are 656e67696e65 = 'engine'",
        'source': 'fragments.json:dex.loader_call_sites',
        'note': 'the name never appears in the dex string pool',
        'chain': 'CH-01',
        'hop': 2,
    },
    {
        'layer': 'L1',
        'kind': 'invokes_loader',
        'src_module': 'classes.dex',
        'src_offset': '0x2bafd6',
        'src_name': 'Lio/flutter/embedding/engine/FlutterJNI;->loadLibrary()V',
        'src_insn': 'fill-array-data payload = ',
        'dst_module': 'classes.dex',
        'dst_offset': '',
        'dst_name': 'string literal "flutter" built at run time',
        'resolved_by': 'payload bytes decoded as ASCII',
        'confidence': 'proven',
        'evidence': 'const-string "flutter" at file 0x2bafd6 in Lio/flutter/embedding/engine/FlutterJNI;->loadLibrary()V',
        'source': 'fragments.json:dex.loader_call_sites',
        'note': 'the name never appears in the dex string pool',
        'chain': 'CH-09',
        'hop': 0,
    },
    {
        'layer': 'L1',
        'kind': 'invokes_loader',
        'src_module': 'classes.dex',
        'src_offset': '0x2bafda',
        'src_name': 'Lio/flutter/embedding/engine/FlutterJNI;->loadLibrary()V',
        'src_insn': 'invoke-static {...}, Ljava/lang/System;->loadLibrary(Ljava/lang/String;)V',
        'dst_module': 'android-runtime',
        'dst_offset': '',
        'dst_name': 'java.lang.System.loadLibrary("flutter")',
        'resolved_by': 'library name from const-string',
        'confidence': 'proven',
        'evidence': 'const-string "flutter" at file 0x2bafd6 in Lio/flutter/embedding/engine/FlutterJNI;->loadLibrary()V',
        'source': 'fragments/F2_dex_natives.txt + fragments.json:dex.loader_call_sites',
        'note': '',
        'chain': 'CH-09',
        'hop': 1,
    },
    {
        'layer': 'L2',
        'kind': 'calls_entry_point',
        'src_module': 'android-runtime',
        'src_offset': '',
        'src_name': 'ART (a Java caller of Lcom/snake/helper/Native;->update)',
        'src_insn': 'call through the fnPtr registered by RegisterNatives',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81eeb0',
        'dst_name': ".mytext fnPtr 0x81eeb0 (decodes as 'ret'; the body starts at 0x81eeb4)",
        'resolved_by': 'the only statically recovered fnPtr of the 13 registrations',
        'confidence': 'strong',
        'evidence': 'F4: site @0xb40a8 entry[1].fnPtr = 0x81eeb0 in .mytext; the instruction at 0x81eeb0 decodes as `ret` and 0x81eeb4 opens a real prologue (`stp x29, x30, [sp, #-0x20]!`), so the pointer as published returns immediately - see the gap list',
        'source': 'fragments/F4b_libengine_mytext.asm',
        'note': '',
        'chain': 'CH-06',
        'hop': 2,
    },
    {
        'layer': 'L2',
        'kind': 'calls_entry_point',
        'src_module': 'android-runtime',
        'src_offset': '',
        'src_name': 'linker (dlopen of libengine.so)',
        'src_insn': 'call DT_INIT/JNI_OnLoad after the .init_array runs',
        'dst_module': 'libengine.so',
        'dst_offset': '0xf3fa0',
        'dst_name': 'JNI_OnLoad',
        'resolved_by': '.dynsym STT_FUNC export',
        'confidence': 'proven',
        'evidence': 'F4: exports 17 defined dynamic symbols, 0 of them Java_*; JNI_OnLoad @0xf3fa0. Ghidra independently places it at 0x1f3fa0 = 0xf3fa0 + 0x100000',
        'source': 'fragments/F4_libengine_jni.txt',
        'note': '',
        'chain': 'CH-03',
        'hop': 5,
    },
    {
        'layer': 'L2',
        'kind': 'loads_library',
        'src_module': 'android-runtime',
        'src_offset': '',
        'src_name': 'System.loadLibrary("engine")',
        'src_insn': 'dlopen',
        'dst_module': 'libengine.so',
        'dst_offset': '',
        'dst_name': 'lib/arm64-v8a/libengine.so',
        'resolved_by': 'SONAME of the committed library',
        'confidence': 'proven',
        'evidence': 'APK member lib/arm64-v8a/libengine.so == repo copy binaries/libengine.so (sha256 f5d751e6bde8f059..., 8,544,568 bytes, match=True)',
        'source': 'fragments/F1_apk_inventory.txt',
        'note': '',
        'chain': 'CH-01',
        'hop': 3,
    },
    {
        'layer': 'L2',
        'kind': 'loads_library',
        'src_module': 'android-runtime',
        'src_offset': '',
        'src_name': 'System.loadLibrary("flutter")',
        'src_insn': 'dlopen',
        'dst_module': 'libflutter.so',
        'dst_offset': '',
        'dst_name': 'lib/arm64-v8a/libflutter.so',
        'resolved_by': 'SONAME of the committed library',
        'confidence': 'proven',
        'evidence': 'APK member lib/arm64-v8a/libflutter.so == repo copy flutter_libs/libflutter.so (sha256 0baa710d6b7f7de2..., 10,714,752 bytes, match=True)',
        'source': 'fragments/F1_apk_inventory.txt',
        'note': '',
        'chain': 'CH-09',
        'hop': 2,
    },
    {
        'layer': 'L3',
        'kind': 'calls_direct',
        'src_module': 'libengine.so',
        'src_offset': '0x81eee4',
        'src_name': '.mytext registered handler (0x81eeb4)',
        'src_insn': 'bl #0xb01c4',
        'dst_module': 'libengine.so',
        'dst_offset': '0xb01c4',
        'dst_name': 'sub_b01c4',
        'resolved_by': '(unresolved) .text offset - 0x84 bytes past the RegisterNatives site at 0xb0140',
        'confidence': 'probable',
        'evidence': '0x81eed8 `mov x2, x0` (x0 = FromReflectedMethod result); 0x81eedc `mov x0, x20` (x20 = the JNIEnv* saved at 0x81eecc); 0x81eee0 `mov x1, x19` (x19 = incoming x2, saved at 0x81eec8); 0x81eee4 `bl #0xb01c4` - env, the original second argument and the reflected java.lang.reflect.Method are forwarded into .text',
        'source': 'fragments/F4b_libengine_mytext.asm:22',
        'note': 'the only hop out of .mytext into the protected body; its target has no symbol',
        'chain': 'CH-06',
        'hop': 4,
    },
    {
        'layer': 'L3',
        'kind': 'calls_direct',
        'src_module': 'libengine.so',
        'src_offset': '0x81ef40',
        'src_name': '.mytext registered handler (0x81eeb4)',
        'src_insn': 'bl #0xb134c',
        'dst_module': 'libengine.so',
        'dst_offset': '0xb134c',
        'dst_name': 'sub_b134c',
        'resolved_by': '(unresolved) .text offset',
        'confidence': 'probable',
        'evidence': '0x81ef34 function entry (`stp x29, x30, [sp, #-0x10]!`); 0x81ef3c `mov x1, x3`; 0x81ef40 `bl #0xb134c` - the second .mytext routine forwards its 4th argument as x1 and does no FromReflectedMethod, so it is not the Method-shaped handler',
        'source': 'fragments/F4b_libengine_mytext.asm:45',
        'note': 'second routine in .mytext; not reachable from the recovered fnPtr 0x81eeb0',
        'chain': 'CH-06',
        'hop': 0,
    },
    {
        'layer': 'L3',
        'kind': 'calls_direct',
        'src_module': 'libengine.so',
        'src_offset': '0xb0088',
        'src_name': 'registration site 0xb0140 (nMethods=1)',
        'src_insn': 'bl #0x7775d8',
        'dst_module': 'libengine.so',
        'dst_offset': '0x7775d8',
        'dst_name': 'sub_7775d8',
        'resolved_by': '(unresolved) no symbol covers this offset in the fragments',
        'confidence': 'probable',
        'evidence': '`0xb0088: bl        #0x7775d8`; arguments staged before the call: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:11',
        'note': '',
        'chain': 'CH-07',
        'hop': 2,
    },
    {
        'layer': 'L3',
        'kind': 'calls_direct',
        'src_module': 'libengine.so',
        'src_offset': '0xb0094',
        'src_name': 'registration site 0xb0140 (nMethods=1)',
        'src_insn': 'bl #0x81f140',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81f140',
        'dst_name': 'sub_81f140',
        'resolved_by': '(unresolved) no symbol covers this offset in the fragments',
        'confidence': 'probable',
        'evidence': '`0xb0094: bl        #0x81f140`; arguments staged before the call: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:14',
        'note': '',
        'chain': 'CH-07',
        'hop': 3,
    },
    {
        'layer': 'L3',
        'kind': 'calls_direct',
        'src_module': 'libengine.so',
        'src_offset': '0xb00e4',
        'src_name': 'registration site 0xb0140 (nMethods=1)',
        'src_insn': 'bl #0x81f250',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81f250',
        'dst_name': 'sub_81f250',
        'resolved_by': "(unresolved) PLT stub - not among the 5 stubs Ghidra's callgraph names",
        'confidence': 'probable',
        'evidence': '0xb00d8 `ldr x0, [sp, #0x30]`; 0xb00dc `mov x1, x24`; 0xb00e0 `mov w2, #8`; 0xb00e4 `bl #0x81f250`; 0xb00e8 `cbnz w0, #0xb0120` - a (ptr, ptr, 8) -> int call whose result is tested, i.e. memcmp-shaped: the 8 decoded bytes are compared before the registration proceeds',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:34',
        'note': 'shape-identified only; the import name needs .rela.plt, which the bundle does not carry',
        'chain': 'CH-07',
        'hop': 5,
    },
    {
        'layer': 'L3',
        'kind': 'calls_direct',
        'src_module': 'libengine.so',
        'src_offset': '0xb4050',
        'src_name': 'registration site 0xb40a8 (nMethods=2)',
        'src_insn': 'bl #0x777fb0',
        'dst_module': 'libengine.so',
        'dst_offset': '0x777fb0',
        'dst_name': 'sub_777fb0',
        'resolved_by': '(unresolved) no symbol covers this offset in the fragments',
        'confidence': 'probable',
        'evidence': '`0xb4050: bl        #0x777fb0`; arguments staged before the call: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:35',
        'note': '',
        'chain': 'CH-05',
        'hop': 4,
    },
    {
        'layer': 'L3',
        'kind': 'calls_direct',
        'src_module': 'libengine.so',
        'src_offset': '0xb405c',
        'src_name': 'registration site 0xb40a8 (nMethods=2)',
        'src_insn': 'bl #0x81f140',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81f140',
        'dst_name': 'sub_81f140',
        'resolved_by': '(unresolved) no symbol covers this offset in the fragments',
        'confidence': 'probable',
        'evidence': '`0xb405c: bl        #0x81f140`; arguments staged before the call: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:38',
        'note': '',
        'chain': 'CH-05',
        'hop': 5,
    },
    {
        'layer': 'L3',
        'kind': 'calls_direct',
        'src_module': 'libengine.so',
        'src_offset': '0xf3988',
        'src_name': 'registration site 0xf3a08 (nMethods=10)',
        'src_insn': 'bl #0x7778a8',
        'dst_module': 'libengine.so',
        'dst_offset': '0x7778a8',
        'dst_name': 'sub_7778a8',
        'resolved_by': '(unresolved) no symbol covers this offset in the fragments',
        'confidence': 'probable',
        'evidence': '`0xf3988: bl        #0x7778a8`; arguments staged before the call: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:25',
        'note': '',
        'chain': 'CH-04',
        'hop': 3,
    },
    {
        'layer': 'L3',
        'kind': 'calls_direct',
        'src_module': 'libengine.so',
        'src_offset': '0xf3994',
        'src_name': 'registration site 0xf3a08 (nMethods=10)',
        'src_insn': 'bl #0x81f140',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81f140',
        'dst_name': 'sub_81f140',
        'resolved_by': '(unresolved) no symbol covers this offset in the fragments',
        'confidence': 'probable',
        'evidence': '`0xf3994: bl        #0x81f140`; arguments staged before the call: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:28',
        'note': '',
        'chain': 'CH-04',
        'hop': 4,
    },
    {
        'layer': 'L3',
        'kind': 'calls_plt',
        'src_module': 'libengine.so',
        'src_offset': '0xb4018',
        'src_name': 'registration site 0xb40a8 (nMethods=2)',
        'src_insn': 'bl #0x81ad58',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81ad58',
        'dst_name': 'FUN_0091ad58',
        'resolved_by': "PLT stub named by Ghidra's callgraph (F7, rebased -0x100000)",
        'confidence': 'strong',
        'evidence': '`0xb4018: bl        #0x81ad58`; arguments staged before the call: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:21',
        'note': '',
        'chain': 'CH-05',
        'hop': 2,
    },
    {
        'layer': 'L3',
        'kind': 'calls_plt',
        'src_module': 'libengine.so',
        'src_offset': '0xb40e8',
        'src_name': 'registration site 0xb40a8 (nMethods=2)',
        'src_insn': 'bl #0x81eff0',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81eff0',
        'dst_name': '__stack_chk_fail',
        'resolved_by': "PLT stub named by Ghidra's callgraph (F7, rebased -0x100000)",
        'confidence': 'strong',
        'evidence': '`0xb40e8: bl        #0x81eff0`; arguments staged before the call: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:73',
        'note': '',
        'chain': 'CH-05',
        'hop': 0,
    },
    {
        'layer': 'L3',
        'kind': 'calls_plt',
        'src_module': 'libengine.so',
        'src_offset': '0xf3944',
        'src_name': 'registration site 0xf3a08 (nMethods=10)',
        'src_insn': 'bl #0x81ad58',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81ad58',
        'dst_name': 'FUN_0091ad58',
        'resolved_by': "PLT stub named by Ghidra's callgraph (F7, rebased -0x100000)",
        'confidence': 'strong',
        'evidence': '`0xf3944: bl        #0x81ad58`; arguments staged before the call: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:8',
        'note': '',
        'chain': 'CH-04',
        'hop': 1,
    },
    {
        'layer': 'L3',
        'kind': 'calls_plt',
        'src_module': 'libengine.so',
        'src_offset': '0xf3a50',
        'src_name': 'registration site 0xf3a08 (nMethods=10)',
        'src_insn': 'bl #0x81eff0',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81eff0',
        'dst_name': '__stack_chk_fail',
        'resolved_by': "PLT stub named by Ghidra's callgraph (F7, rebased -0x100000)",
        'confidence': 'strong',
        'evidence': '`0xf3a50: bl        #0x81eff0`; arguments staged before the call: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:75',
        'note': '',
        'chain': 'CH-04',
        'hop': 0,
    },
    {
        'layer': 'L3',
        'kind': 'calls_plt',
        'src_module': 'libengine.so',
        'src_offset': '0xf3fd8',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'bl #0x81f110',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81f110',
        'dst_name': 'sysconf',
        'resolved_by': "PLT stub named by Ghidra's callgraph (F7, rebased -0x100000)",
        'confidence': 'strong',
        'evidence': '`0xf3fd8: bl        #0x81f110`; arguments staged before the call: -',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:16',
        'note': '',
        'chain': 'CH-03',
        'hop': 1,
    },
    {
        'layer': 'L3',
        'kind': 'calls_plt',
        'src_module': 'libengine.so',
        'src_offset': '0xf406c',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'bl #0x81f120',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81f120',
        'dst_name': 'rand',
        'resolved_by': "PLT stub named by Ghidra's callgraph (F7, rebased -0x100000)",
        'confidence': 'strong',
        'evidence': '`0xf406c: bl        #0x81f120`; arguments staged before the call: -',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:53',
        'note': '',
        'chain': 'CH-03',
        'hop': 4,
    },
    {
        'layer': 'L3',
        'kind': 'calls_plt',
        'src_module': 'libengine.so',
        'src_offset': '0xf40ac',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'bl #0x81ad58',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81ad58',
        'dst_name': 'FUN_0091ad58',
        'resolved_by': "PLT stub named by Ghidra's callgraph (F7, rebased -0x100000)",
        'confidence': 'strong',
        'evidence': '`0xf40ac: bl        #0x81ad58`; arguments staged before the call: -',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:69',
        'note': '',
        'chain': 'CH-03',
        'hop': 7,
    },
    {
        'layer': 'L3',
        'kind': 'calls_plt',
        'src_module': 'libengine.so',
        'src_offset': '0xf40e8',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'bl #0x81f110',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81f110',
        'dst_name': 'sysconf',
        'resolved_by': "PLT stub named by Ghidra's callgraph (F7, rebased -0x100000)",
        'confidence': 'strong',
        'evidence': '`0xf40e8: bl        #0x81f110`; arguments staged before the call: -',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:84',
        'note': '',
        'chain': 'CH-03',
        'hop': 0,
    },
    {
        'layer': 'L3',
        'kind': 'calls_plt',
        'src_module': 'libengine.so',
        'src_offset': '0xf446c',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'bl #0x81f0e0',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81f0e0',
        'dst_name': 'strlen',
        'resolved_by': "PLT stub named by Ghidra's callgraph (F7, rebased -0x100000)",
        'confidence': 'strong',
        'evidence': '`0xf446c: bl        #0x81f0e0`; arguments staged before the call: -',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:309',
        'note': '',
        'chain': 'CH-03',
        'hop': 12,
    },
    {
        'layer': 'L3',
        'kind': 'calls_plt',
        'src_module': 'libengine.so',
        'src_offset': '0xf45bc',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'bl #0x81f0e0',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81f0e0',
        'dst_name': 'strlen',
        'resolved_by': "PLT stub named by Ghidra's callgraph (F7, rebased -0x100000)",
        'confidence': 'strong',
        'evidence': '`0xf45bc: bl        #0x81f0e0`; arguments staged before the call: -',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:393',
        'note': '',
        'chain': 'CH-03',
        'hop': 0,
    },
    {
        'layer': 'L3',
        'kind': 'calls_syscall',
        'src_module': 'libengine.so',
        'src_offset': '0xb3fe4',
        'src_name': 'registration site 0xb40a8 (nMethods=2)',
        'src_insn': 'svc #0',
        'dst_module': 'kernel',
        'dst_offset': '0x35',
        'dst_name': 'fchmodat',
        'resolved_by': 'syscall number staged in w8/x8 before svc (asm-generic/unistd.h, arm64)',
        'confidence': 'proven',
        'evidence': '0xb3fd4 `stur x8, [x29, #-0x40]`; 0xb3fd8 `ldur x8, [x29, #-0x40]`; 0xb3fdc `ldr x0, [x8]`; 0xb3fe0 `mov x8, #0x35`; 0xb3fe4 `svc #0` - syscall 53 (fchmodat) with only x0 staged, the value having been round-tripped through the stack from an obfuscated immediate (0xb3fc8-0xb3fd0 build 0x33804ef2)',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:8',
        'note': 'first instruction of the window: the site opens with a syscall, not with a call',
        'chain': 'CH-05',
        'hop': 1,
    },
    {
        'layer': 'L3',
        'kind': 'calls_syscall',
        'src_module': 'libengine.so',
        'src_offset': '0xf4018',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'svc #0',
        'dst_module': 'kernel',
        'dst_offset': '0xde',
        'dst_name': 'mmap',
        'resolved_by': 'syscall number staged in w8/x8 before svc (asm-generic/unistd.h, arm64)',
        'confidence': 'proven',
        'evidence': '`0xf4018: svc       #0` with w8 = #0xde = 222 = mmap; arguments visible in this window: prot=0x7 (R|W|X), flags=0x22 (MAP_PRIVATE|MAP_ANONYMOUS), fd=0xffffffffffffffff',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:32',
        'note': '',
        'chain': 'CH-03',
        'hop': 2,
    },
    {
        'layer': 'L3',
        'kind': 'calls_syscall',
        'src_module': 'libengine.so',
        'src_offset': '0xf411c',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'svc #0',
        'dst_module': 'kernel',
        'dst_offset': '0xde',
        'dst_name': 'mmap',
        'resolved_by': 'syscall number staged in w8/x8 before svc (asm-generic/unistd.h, arm64)',
        'confidence': 'proven',
        'evidence': '`0xf411c: svc       #0` with w8 = #0xde = 222 = mmap; arguments visible in this window: prot=0x7 (R|W|X), flags=0x22 (MAP_PRIVATE|MAP_ANONYMOUS), fd=0xffffffffffffffff',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:97',
        'note': '',
        'chain': 'CH-03',
        'hop': 9,
    },
    {
        'layer': 'L3',
        'kind': 'calls_syscall',
        'src_module': 'libengine.so',
        'src_offset': '0xf4428',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'svc #0',
        'dst_module': 'kernel',
        'dst_offset': '0x35',
        'dst_name': 'fchmodat',
        'resolved_by': 'syscall number staged in w8/x8 before svc (asm-generic/unistd.h, arm64)',
        'confidence': 'proven',
        'evidence': '0xf4418 `str x26, [sp, #0x10]`; 0xf441c `ldr x8, [sp, #0x10]`; 0xf4420 `ldr x0, [x8]`; 0xf4424 `mov x8, #0x35`; 0xf4428 `svc #0` - the syscall number is proven (53 = fchmodat) but only x0 is staged, and it is a word read back out of the generated page, so the arguments are NOT recoverable from the image',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:292',
        'note': 'reached when the second generated call returned non-zero (0xf43f8 `cbz x0, #0xf4430`)',
        'chain': 'CH-03',
        'hop': 11,
    },
    {
        'layer': 'L3',
        'kind': 'calls_syscall',
        'src_module': 'libengine.so',
        'src_offset': '0xf4458',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'svc #0',
        'dst_module': 'kernel',
        'dst_offset': '0x35',
        'dst_name': 'fchmodat',
        'resolved_by': 'syscall number staged in w8/x8 before svc (asm-generic/unistd.h, arm64)',
        'confidence': 'proven',
        'evidence': '0xf4448 `str w8, [sp, #0x10]`; 0xf444c `ldr x8, [sp, #0x10]`; 0xf4450 `ldr x0, [x8]`; 0xf4454 `mov x8, #0x35`; 0xf4458 `svc #0` - same shape as 0xf4428 on the other branch of the `cbz`',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:304',
        'note': 'the pair brackets the runtime check, i.e. both outcomes end in the same syscall',
        'chain': 'CH-03',
        'hop': 0,
    },
    {
        'layer': 'L3',
        'kind': 'calls_syscall_stub',
        'src_module': 'libengine.so',
        'src_offset': '0xb0068',
        'src_name': 'registration site 0xb0140 (nMethods=1)',
        'src_insn': 'blr x20',
        'dst_module': 'kernel',
        'dst_offset': '0xde',
        'dst_name': 'syscall 222 (mmap) via function pointer in x20',
        'resolved_by': 'syscall number staged in w6 = #0xde; x0-x5 hold the mmap arguments',
        'confidence': 'strong',
        'evidence': '`0xb0068: blr       x20` with `mov w6, #0xde` = 222 = mmap staged before it; arguments visible in this window: none staged inside this window',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:3',
        'note': '',
        'chain': 'CH-07',
        'hop': 1,
    },
    {
        'layer': 'L3',
        'kind': 'calls_syscall_stub',
        'src_module': 'libengine.so',
        'src_offset': '0xb403c',
        'src_name': 'registration site 0xb40a8 (nMethods=2)',
        'src_insn': 'blr x19',
        'dst_module': 'kernel',
        'dst_offset': '0xde',
        'dst_name': 'syscall 222 (mmap) via function pointer in x19',
        'resolved_by': 'syscall number staged in w6 = #0xde; x0-x5 hold the mmap arguments',
        'confidence': 'strong',
        'evidence': '`0xb403c: blr       x19` with `mov w6, #0xde` = 222 = mmap staged before it; arguments visible in this window: length=0x4, prot=0x7 (R|W|X), flags=0x22 (MAP_PRIVATE|MAP_ANONYMOUS), fd=0xffffffffffffffff',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:30',
        'note': '',
        'chain': 'CH-05',
        'hop': 3,
    },
    {
        'layer': 'L3',
        'kind': 'calls_syscall_stub',
        'src_module': 'libengine.so',
        'src_offset': '0xf3968',
        'src_name': 'registration site 0xf3a08 (nMethods=10)',
        'src_insn': 'blr x19',
        'dst_module': 'kernel',
        'dst_offset': '0xde',
        'dst_name': 'syscall 222 (mmap) via function pointer in x19',
        'resolved_by': 'syscall number staged in w6 = #0xde; x0-x5 hold the mmap arguments',
        'confidence': 'strong',
        'evidence': '`0xf3968: blr       x19` with `mov w6, #0xde` = 222 = mmap staged before it; arguments visible in this window: length=0x18, prot=0x7 (R|W|X), flags=0x22 (MAP_PRIVATE|MAP_ANONYMOUS), fd=0xffffffffffffffff',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:17',
        'note': '',
        'chain': 'CH-04',
        'hop': 2,
    },
    {
        'layer': 'L3',
        'kind': 'calls_vtable0',
        'src_module': 'libengine.so',
        'src_offset': '0xb00c4',
        'src_name': 'registration site 0xb0140 (nMethods=1)',
        'src_insn': 'blr x8',
        'dst_module': 'libengine.so',
        'dst_offset': '',
        'dst_name': '*x25 (first word of the object returned earlier)',
        'resolved_by': '(unresolved) virtual dispatch - the vtable is filled at run time',
        'confidence': 'probable',
        'evidence': '`0xb00c4: blr       x8` after `ldr x8, [x25]`; arguments staged: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:26',
        'note': '',
        'chain': 'CH-07',
        'hop': 4,
    },
    {
        'layer': 'L3',
        'kind': 'calls_vtable0',
        'src_module': 'libengine.so',
        'src_offset': '0xb407c',
        'src_name': 'registration site 0xb40a8 (nMethods=2)',
        'src_insn': 'blr x8',
        'dst_module': 'libengine.so',
        'dst_offset': '',
        'dst_name': '*x22 (first word of the object returned earlier)',
        'resolved_by': '(unresolved) virtual dispatch - the vtable is filled at run time',
        'confidence': 'probable',
        'evidence': '`0xb407c: blr       x8` after `ldr x8, [x22]`; arguments staged: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:46',
        'note': '',
        'chain': 'CH-05',
        'hop': 6,
    },
    {
        'layer': 'L3',
        'kind': 'calls_vtable0',
        'src_module': 'libengine.so',
        'src_offset': '0xf39c4',
        'src_name': 'registration site 0xf3a08 (nMethods=10)',
        'src_insn': 'blr x8',
        'dst_module': 'libengine.so',
        'dst_offset': '',
        'dst_name': '*x21 (first word of the object returned earlier)',
        'resolved_by': '(unresolved) virtual dispatch - the vtable is filled at run time',
        'confidence': 'probable',
        'evidence': '`0xf39c4: blr       x8` after `ldr x8, [x21]`; arguments staged: -',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:40',
        'note': '',
        'chain': 'CH-04',
        'hop': 5,
    },
    {
        'layer': 'L3',
        'kind': 'computes_branch',
        'src_module': 'libengine.so',
        'src_offset': '0xf4054',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'br x10',
        'dst_module': 'libengine.so',
        'dst_offset': '',
        'dst_name': 'dispatch table at 0x125d4 (adrp 0x12000 + 0x5d4), 4 relative offsets',
        'resolved_by': 'adrp/add at 0xf3fe0+0xf3ff8 build x26 = 0x125d4; `ldrsw x11,[x26,x9,lsl#2]` with x9 = x27 & 3 selects one of 4 signed offsets added to the PC at 0xf4048',
        'confidence': 'strong',
        'evidence': '0xf4048 `adr x10, #0xf4048`; 0xf404c `ldrsw x11, [x26, x9, lsl #2]`; 0xf4050 `add x10, x10, x11`; 0xf4054 `br x10` - the four table words at 0x125d4..0x125e0 are file bytes this bundle does not contain, so the four targets stay open (recipe: read 4 little-endian int32 at libengine.so+0x125d4)',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:47',
        'note': 'switch-shaped dispatcher inside the loop that writes the generated page',
        'chain': 'CH-03',
        'hop': 3,
    },
    {
        'layer': 'L3',
        'kind': 'jumps_into_generated',
        'src_module': 'libengine.so',
        'src_offset': '0xf40e0',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'blr x8',
        'dst_module': 'libengine.so',
        'dst_offset': '',
        'dst_name': 'generated code in the first RWX page (the mmap result stored at sp+0x10)',
        'resolved_by': 'x8 = [sp,#0x10] = pages[0], written by `str x0, [x25, x22, lsl #3]` at 0xf4020 with x25 = sp+0x10 (0xf3ff4) and x0 = the mmap return at 0xf4018',
        'confidence': 'proven',
        'evidence': '0xf3ff4 `add x25, sp, #0x10`; 0xf4018 `svc #0` (mmap, prot=RWX); 0xf4020 `str x0, [x25, x22, lsl #3]`; 0xf40c4 `ldr x8, [sp, #0x10]`; 0xf40e0 `blr x8` - control leaves the static image',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:82',
        'note': 'first of the 2 blr in JNI_OnLoad (F4: blr_count = 2)',
        'chain': 'CH-03',
        'hop': 8,
    },
    {
        'layer': 'L3',
        'kind': 'jumps_into_generated',
        'src_module': 'libengine.so',
        'src_offset': '0xf43f4',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'blr x8',
        'dst_module': 'libengine.so',
        'dst_offset': '',
        'dst_name': 'generated table in the second RWX page (x8 = mmap result of 0xf411c)',
        'resolved_by': 'x8 = x0 of the second mmap (0xf4120 `mov x8, x0`); 0xf41f8-0xf43c8 fill [x8+0x550 .. x8+0x5e8] with values built by shifting immediates through counts loaded from .bss 0x828048..0x828088',
        'confidence': 'proven',
        'evidence': '0xf411c `svc #0` (mmap, prot=RWX); 0xf4120 `mov x8, x0`; 0xf4190 `ldr x9, [x9, #0x48]` / 0xf41a0 `ldr x10, [x10, #0x50]` (.bss shift counts); 0xf41f8 `str x9, [x8, #0x550]` ... 0xf43c8 `str x9, [x8, #0x5e8]`; 0xf43f0 `mov x6, x8`; 0xf43f4 `blr x8`; 0xf43f8 `cbz x0, #0xf4430`',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:279',
        'note': 'the callee returns the value that selects the 0xf4430 / 0xf442c path - a runtime check whose result is consumed but whose code is not in the image',
        'chain': 'CH-03',
        'hop': 10,
    },
    {
        'layer': 'L3',
        'kind': 'writes_generated_code',
        'src_module': 'libengine.so',
        'src_offset': '0xf4078',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'str w8, [x21, x27, lsl #2]',
        'dst_module': 'libengine.so',
        'dst_offset': '',
        'dst_name': 'RWX page from the mmap at 0xf4018 (x21 = page, x27 = word index)',
        'resolved_by': '`mov w28, #0x14000000` at 0xf4040 is the AArch64 unconditional-branch opcode; 0xf406c-0xf4074 blend it with rand() and mask 0x3ffffff',
        'confidence': 'proven',
        'evidence': '0xf4040 `mov w28, #0x14000000`; 0xf4044 `mov w19, #0x3ffffff`; 0xf4070 `and w8, w0, w19`; 0xf4074 `orr w8, w8, w28`; 0xf4078 `str w8, [x21, x27, lsl #2]` - a `B <imm26>` is written word by word into the page mmap returned',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:56',
        'note': 'this is why no static tool sees the registration code: it is emitted at load time',
        'chain': 'CH-03',
        'hop': 5,
    },
    {
        'layer': 'L3',
        'kind': 'writes_generated_code',
        'src_module': 'libengine.so',
        'src_offset': '0xf40a0',
        'src_name': 'JNI_OnLoad',
        'src_insn': 'str w10, [x8]',
        'dst_module': 'libengine.so',
        'dst_offset': '',
        'dst_name': 'previous RWX page (x8 = pages[n-1]); the branch is aimed at x21 = pages[n]',
        'resolved_by': '0xf4090 stages the opcode, 0xf4098 computes the delta, 0xf409c packs it',
        'confidence': 'proven',
        'evidence': '0xf4090 `mov w10, #0x14000000`; 0xf4094 `ldr x8, [x25, w8, uxtw #3]` (previous page); 0xf4098 `sub w9, w21, w8`; 0xf409c `bfxil w10, w9, #2, #0x1a`; 0xf40a0 `str w10, [x8]` - page n-1 is patched with `B (page_n - page_{n-1}) >> 2`, chaining the pages',
        'source': 'fragments/F4c_libengine_JNI_OnLoad.asm:66',
        'note': 'the pages form a linked trampoline chain, each one branching to the next',
        'chain': 'CH-03',
        'hop': 6,
    },
    {
        'layer': 'L4',
        'kind': 'binds_fnptr_to_dex',
        'src_module': 'libengine.so',
        'src_offset': '0xb0140',
        'src_name': 'RegisterNatives site 0xb0140',
        'src_insn': 'nMethods = 1',
        'dst_module': 'classes.dex',
        'dst_offset': '',
        'dst_name': 'com/snake/helper/Native (pjowqpxe, by count-elimination)',
        'resolved_by': 'LINKAGE.md attribution: FindClass name length + decode-loop bounds + count-elimination; consumes all 13 declarations exactly',
        'confidence': 'probable',
        'evidence': 'byte-decode loop at 0xb00d0 runs 8 times (strb + add x20,x20,#1 + cmp x20,#8 + b.ne)  [all loop bounds in window: [8]]',
        'source': 'fragments.json:libengine.register_natives_sites',
        'note': '',
        'chain': 'CH-07',
        'hop': 0,
    },
    {
        'layer': 'L4',
        'kind': 'binds_fnptr_to_dex',
        'src_module': 'libengine.so',
        'src_offset': '0xb40a8',
        'src_name': 'RegisterNatives site 0xb40a8',
        'src_insn': 'nMethods = 2',
        'dst_module': 'classes.dex',
        'dst_offset': '',
        'dst_name': 'com/snake/helper/flagger (na, nb)',
        'resolved_by': 'LINKAGE.md attribution: FindClass name length + decode-loop bounds + count-elimination; consumes all 13 declarations exactly',
        'confidence': 'probable',
        'evidence': 'byte-decode loop at 0xb4088 runs 3 times (strb + add x19,x19,#1 + cmp x19,#3 + b.ne)  [all loop bounds in window: [2, 3]]',
        'source': 'fragments.json:libengine.register_natives_sites',
        'note': '',
        'chain': 'CH-05',
        'hop': 0,
    },
    {
        'layer': 'L4',
        'kind': 'binds_fnptr_to_dex',
        'src_module': 'libengine.so',
        'src_offset': '0xf3a08',
        'src_name': 'RegisterNatives site 0xf3a08',
        'src_insn': 'nMethods = 10',
        'dst_module': 'classes.dex',
        'dst_offset': '',
        'dst_name': 'com/snake/helper/Native (10 of its 11 declarations)',
        'resolved_by': 'LINKAGE.md attribution: FindClass name length + decode-loop bounds + count-elimination; consumes all 13 declarations exactly',
        'confidence': 'strong',
        'evidence': 'FindClass at 0xf39e4; byte-decode loop at 0xf39d0 runs 23 times (strb + add x19,x19,#1 + cmp x19,#23 + b.ne), so the JNI class name it materialises is that many characters long  [all loop bounds in window: [23]]',
        'source': 'fragments.json:libengine.register_natives_sites',
        'note': '',
        'chain': 'CH-04',
        'hop': 0,
    },
    {
        'layer': 'L4',
        'kind': 'calls_jni_slot',
        'src_module': 'libengine.so',
        'src_offset': '0x81eed4',
        'src_name': '.mytext registered handler (0x81eeb4)',
        'src_insn': 'blr x8',
        'dst_module': 'android-runtime',
        'dst_offset': '0x38',
        'dst_name': 'JNIEnv->FromReflectedMethod (slot 7)',
        'resolved_by': 'JNIEnv function-table offset (jni.h order)',
        'confidence': 'proven',
        'evidence': '`0x81eed4: blr       x8` reached through `blr` of the value loaded by `ldr x8, [x8, #0x38]`; the table pointer itself came from `ldr x8, [x0]`',
        'source': 'fragments/F4b_libengine_mytext.asm:18',
        'note': '',
        'chain': 'CH-06',
        'hop': 3,
    },
    {
        'layer': 'L4',
        'kind': 'calls_jni_slot',
        'src_module': 'libengine.so',
        'src_offset': '0xb018c',
        'src_name': 'registration site 0xb0140 (nMethods=1)',
        'src_insn': 'blr x8',
        'dst_module': 'android-runtime',
        'dst_offset': '0x88',
        'dst_name': 'JNIEnv->ExceptionClear (slot 17)',
        'resolved_by': 'JNIEnv function-table offset (jni.h order)',
        'confidence': 'proven',
        'evidence': '0xb0180 `ldr x8, [x19]`; 0xb0184 `ldr x8, [x8, #0x88]`; 0xb0188 `mov x0, x19`; 0xb018c `blr x8` - slot 17 = ExceptionClear(env), reached on the failure path `tbnz w0, #0x1f, #0xb0190` after RegisterNatives returned < 0',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:76',
        'note': 'error path of the registration: clear the pending JNI exception',
        'chain': 'CH-07',
        'hop': 7,
    },
    {
        'layer': 'L4',
        'kind': 'finds_class',
        'src_module': 'libengine.so',
        'src_offset': '0xf39e8',
        'src_name': 'registration site 0xf3a08 (nMethods=10)',
        'src_insn': 'blr x8',
        'dst_module': 'android-runtime',
        'dst_offset': '0x30',
        'dst_name': 'JNIEnv->FindClass (slot 6)',
        'resolved_by': 'JNIEnv function-table offset (jni.h order)',
        'confidence': 'proven',
        'evidence': "0xf39d8 `ldr x8, [x24]`; 0xf39dc `mov x0, x24`; 0xf39e0 `mov x1, x20`; 0xf39e4 `ldr x8, [x8, #0x30]`; 0xf39e8 `blr x8` - FindClass(env, x20) where x20 is the buffer the 23-iteration decode loop at 0xf39b8-0xf39d4 just filled, so the class name is 23 characters: 'com/snake/helper/Native'",
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:49',
        'note': 'the only FindClass among the 3 registration windows; the other two reuse a class handle they did not materialise here',
        'chain': 'CH-04',
        'hop': 6,
    },
    {
        'layer': 'L4',
        'kind': 'registers_natives',
        'src_module': 'libengine.so',
        'src_offset': '0xb0144',
        'src_name': 'registration site 0xb0140 (nMethods=1)',
        'src_insn': 'blr x8',
        'dst_module': 'android-runtime',
        'dst_offset': '0x6b8',
        'dst_name': 'JNIEnv->RegisterNatives (slot 215)',
        'resolved_by': 'JNIEnv function-table offset (jni.h order)',
        'confidence': 'proven',
        'evidence': '`0xb0144: blr       x8` reached through `blr` of the value loaded by `ldr x8, [x8, #0x6b8]`; the table pointer itself came from `ldr x8, [x25]`',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:58',
        'note': '',
        'chain': 'CH-07',
        'hop': 6,
    },
    {
        'layer': 'L4',
        'kind': 'registers_natives',
        'src_module': 'libengine.so',
        'src_offset': '0xb40b4',
        'src_name': 'registration site 0xb40a8 (nMethods=2)',
        'src_insn': 'blr x8',
        'dst_module': 'android-runtime',
        'dst_offset': '0x6b8',
        'dst_name': 'JNIEnv->RegisterNatives (slot 215)',
        'resolved_by': 'JNIEnv function-table offset (jni.h order)',
        'confidence': 'proven',
        'evidence': '`0xb40b4: blr       x8` reached through `blr` of the value loaded by `ldr x8, [x8, #0x6b8]`; the table pointer itself came from `ldr x8, [x22]`',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:60',
        'note': '',
        'chain': 'CH-05',
        'hop': 8,
    },
    {
        'layer': 'L4',
        'kind': 'registers_natives',
        'src_module': 'libengine.so',
        'src_offset': '0xf3a0c',
        'src_name': 'registration site 0xf3a08 (nMethods=10)',
        'src_insn': 'blr x8',
        'dst_module': 'android-runtime',
        'dst_offset': '0x6b8',
        'dst_name': 'JNIEnv->RegisterNatives (slot 215)',
        'resolved_by': 'JNIEnv function-table offset (jni.h order)',
        'confidence': 'proven',
        'evidence': '`0xf3a0c: blr       x8` reached through `blr` of the value loaded by `ldr x8, [x8, #0x6b8]`; the table pointer itself came from `ldr x8, [x21]`',
        'source': 'fragments/F4d_libengine_regnatives_windows.asm:58',
        'note': '',
        'chain': 'CH-04',
        'hop': 7,
    },
    {
        'layer': 'L4',
        'kind': 'rejected_slot_load',
        'src_module': 'libengine.so',
        'src_offset': '0x79d338',
        'src_name': '0x6b8-pattern load',
        'src_insn': 'adrp x8,#0x828000 at file 0x79d32c',
        'dst_module': 'libengine.so',
        'dst_offset': '',
        'dst_name': 'not a JNIEnv call (base = global)',
        'resolved_by': 'the base register points at .bss/.got, not at *JNIEnv',
        'confidence': 'proven',
        'evidence': 'adrp x8,#0x828000 at file 0x79d32c — points at 0x828000 (.bss), not at JNIEnv',
        'source': 'fragments.json:libengine.slot_0x6b8_loads',
        'note': '',
        'chain': '',
        'hop': 0,
    },
    {
        'layer': 'L4',
        'kind': 'rejected_slot_load',
        'src_module': 'libengine.so',
        'src_offset': '0x7fea74',
        'src_name': '0x6b8-pattern load',
        'src_insn': 'adrp x8,#0x839000 at file 0x7fea70',
        'dst_module': 'libengine.so',
        'dst_offset': '',
        'dst_name': 'not a JNIEnv call (base = global)',
        'resolved_by': 'the base register points at .bss/.got, not at *JNIEnv',
        'confidence': 'proven',
        'evidence': 'adrp x8,#0x839000 at file 0x7fea70 — points at 0x839000 (.bss), not at JNIEnv',
        'source': 'fragments.json:libengine.slot_0x6b8_loads',
        'note': '',
        'chain': '',
        'hop': 0,
    },
    {
        'layer': 'L4',
        'kind': 'rejected_slot_load',
        'src_module': 'libengine.so',
        'src_offset': '0x81f514',
        'src_name': '0x6b8-pattern load',
        'src_insn': 'adrp x16,#0x826000 at file 0x81f510',
        'dst_module': 'libengine.so',
        'dst_offset': '',
        'dst_name': 'not a JNIEnv call (base = global)',
        'resolved_by': 'the base register points at .bss/.got, not at *JNIEnv',
        'confidence': 'proven',
        'evidence': 'adrp x16,#0x826000 at file 0x81f510 — points at 0x826000 (.got), not at JNIEnv',
        'source': 'fragments.json:libengine.slot_0x6b8_loads',
        'note': '',
        'chain': '',
        'hop': 0,
    },
    {
        'layer': 'L4',
        'kind': 'stages_fnptr',
        'src_module': 'libengine.so',
        'src_offset': '0xb40b0',
        'src_name': 'registration site 0xb40a8',
        'src_insn': 'stp/str x9 -> sp+0x48 (JNINativeMethod[1].fnPtr)',
        'dst_module': 'libengine.so',
        'dst_offset': '0x81eeb0',
        'dst_name': '.mytext 0x81eeb0 (exec=True) - the only fnPtr of the 13 that survives static analysis',
        'resolved_by': 'absolute value staged by adrp+add inside the same window',
        'confidence': 'proven',
        'evidence': '0xb409c: x2, sp, #0x20 — the JNINativeMethod[] is assembled on the stack, so name/sig/fnPtr are runtime values; the stores into that frame below are what can still be recovered statically; the value written is 0x81eeb0, which lies inside .mytext (0x81eeac + 244 bytes, exec=True, write=False)',
        'source': 'fragments.json:libengine.register_natives_sites',
        'note': '',
        'chain': 'CH-05',
        'hop': 7,
    },
    {
        'layer': 'L6',
        'kind': 'calls_entry_point',
        'src_module': 'android-runtime',
        'src_offset': '',
        'src_name': 'linker (dlopen of libflutter.so)',
        'src_insn': 'call JNI_OnLoad',
        'dst_module': 'libflutter.so',
        'dst_offset': '',
        'dst_name': 'JNI_OnLoad',
        'resolved_by': '.dynsym export present (offset not recorded in F6)',
        'confidence': 'proven',
        'evidence': "F6: exports 46 defined dynamic symbols, 0 Java_*, JNI_OnLoad present - so the engine binds FlutterJNI's 41 natives with RegisterNatives at load time, the same mechanism libengine.so uses for the 13 custom natives",
        'source': 'fragments/F6_libflutter_version.txt',
        'note': '',
        'chain': 'CH-09',
        'hop': 3,
    },
]


# ---------------------------------------------------------------------------
# Extension point: add your own instruction/offset hops here.
# Example:
#   EXTRA_ANNOTATIONS = [
#       {
#           "layer": "L3", "kind": "calls_direct",
#           "src_module": "libengine.so", "src_offset": "0x1234",
#           "src_name": "my new window", "src_insn": "bl #0x5678",
#           "dst_module": "libengine.so", "dst_offset": "0x5678",
#           "dst_name": "sub_5678", "resolved_by": "analyst",
#           "confidence": "probable", "evidence": "...",
#           "source": "analyst-note", "chain": "CH-12", "hop": 1,
#       },
#   ]
# ---------------------------------------------------------------------------
EXTRA_ANNOTATIONS: List[Dict[str, Any]] = []

