"""Rendering: mermaid diagrams + markdown report + baseline comparison."""

from __future__ import annotations

from collections import Counter
from typing import Any, Dict, List, Tuple

from .graph import CallGraph
from .schema import KINDS, LAYERS, Chain, Edge, node_id_for


# --------------------------------------------------------------------------
# mermaid
# --------------------------------------------------------------------------

def _short(node_id: str, maxlen: int = 44) -> str:
    s = node_id.replace('"', "'")
    return s if len(s) <= maxlen else s[: maxlen - 1] + "…"


def mermaid_chain(chain: Chain, graph: CallGraph) -> str:
    """Linear flowchart of one resolved chain."""
    lines = ["flowchart LR"]
    for h in chain.hops:
        e = graph.by_id.get(h.edge_id)
        if e is None:
            lines.append(f"    H{h.n}[\"hop {h.n}: UNRESOLVED<br/>{h.text[:60]}\"]")
            continue
        src = _short(node_id_for(e.src_module, e.src_name, e.src_offset))
        dst = _short(node_id_for(e.dst_module, e.dst_name, e.dst_offset))
        label = (e.src_insn or e.kind).replace('"', "'")[:60]
        lines.append(f"    {e.edge_id}S[\"{src}\"] -->|\"{e.edge_id} {label}\"| {e.edge_id}D[\"{dst}\"]")
    return "\n".join(lines) + "\n"


OVERVIEW_MERMAID = """flowchart LR
  DEX[classes.dex<br/>invoke offsets] -->|CH-01 loadLibrary 'engine'| LOAD[linker / .init_array]
  LOAD -->|CH-02 44 constructors| INIT[libengine.so .text]
  LOAD -->|CH-01| ONLOAD[JNI_OnLoad 0xf3fa0]
  ONLOAD -->|CH-03 mmap RWX + B opcode| GEN[generated pages]
  ONLOAD -->|CH-03 blr| GEN
  INIT -->|CH-04/05/07| REG[RegisterNatives x3]
  REG -->|CH-05 fnPtr 0x81eeb0| MYT[.mytext handler]
  MYT -->|CH-06 FromReflectedMethod + bl 0xb01c4| INIT
  REG -->|CH-04/05/07 attribution| NAT[com/snake/helper/*]
  DEX -->|CH-08 20 invoke sites| NAT
  NAT -.->|CH-06 ART calls fnPtr| MYT
  DEX -->|CH-09 loadLibrary 'flutter'| FL[libflutter.so JNI_OnLoad]
  DART[libapp.so Dart AOT] -->|CH-10 MethodCall handlers + 11 engine symbols| FL
  DART -->|CH-11 decoded bl/b edges| DSTUB[Dart runtime stubs<br/>AwaitStub, InitAsyncStub, ...]
"""


# --------------------------------------------------------------------------
# markdown report
# --------------------------------------------------------------------------

def markdown_report(
    graph: CallGraph,
    chains: List[Chain],
    checks: List[Dict[str, str]],
    meta: Dict[str, Any],
    hot: List[Dict[str, Any]],
) -> str:
    stats = graph.stats()
    out: List[str] = []
    out.append("# Call linkage (สายการเรียก) — rebuilt report")
    out.append("")
    out.append(f"_generated by `tools/build_call_linkage.py` from `{meta.get('bundle')}`"
               f" (fingerprint `{meta.get('bundle_fingerprint')}`,"
               f" {meta.get('bundle_files')} files)_")
    out.append("")
    out.append("## Summary")
    out.append("")
    out.append(f"- **{stats['edges']} hops**, **{stats['nodes']} nodes**,"
               f" **{len(chains)} chains**")
    out.append(f"- confidence: " + ", ".join(f"{k}={v}" for k, v in sorted(stats["by_confidence"].items())))
    out.append("")
    out.append("| layer | what it covers | hops |")
    out.append("|---|---|---|")
    for layer in ("L1", "L2", "L3", "L4", "L5", "L6"):
        out.append(f"| `{layer}` {LAYERS[layer]['name']} |"
                   f" {LAYERS[layer]['description']} | {stats['by_layer'].get(layer, 0)} |")
    out.append("")
    out.append("| chain | title | layers | hops |")
    out.append("|---|---|---|---|")
    for c in chains:
        title = c.title_th or c.title
        out.append(f"| `{c.id}` | {title} | {c.layer_path} | {len(c.hops)} |")
    out.append("")
    out.append("```mermaid")
    out.append(OVERVIEW_MERMAID.rstrip("\n"))
    out.append("```")
    out.append("")
    for c in chains:
        out.append(f"## `{c.id}` — {c.title_th or c.title}")
        out.append("")
        out.append(f"*{c.layer_path}* · {len(c.hops)} hops")
        out.append("")
        if c.goal:
            out.append(c.goal)
            out.append("")
        out.append("| # | caller | instruction | callee | conf. | hop note |")
        out.append("|---|---|---|---|---|---|")
        for h in c.hops:
            e = graph.by_id.get(h.edge_id)
            if e is None:
                out.append(f"| {h.n} | — | — | — | — | {h.text} **[UNRESOLVED]** |")
                continue
            caller = f"`{e.src_module}`+`{e.src_offset}`" if e.src_offset else f"`{e.src_module}`"
            callee = f"`{e.dst_module}`+`{e.dst_offset}`" if e.dst_offset else f"`{e.dst_module}`"
            out.append(f"| {h.n} | {caller} | `{e.src_insn[:80]}` | {callee} |"
                       f" {e.confidence} | {h.text} |")
        out.append("")
        out.append("```mermaid")
        out.append(mermaid_chain(c, graph).rstrip("\n"))
        out.append("```")
        out.append("")
    out.append("## Hottest Dart targets (fan-in)")
    out.append("")
    out.append("| target | fan-in | name |")
    out.append("|---|---|---|")
    for t in hot[:25]:
        out.append(f"| `{t['module']}`+`{t['offset']}` | {t['fan_in']} | {t['name']} |")
    out.append("")
    out.append("## Verification")
    out.append("")
    out.append("| result | check | detail |")
    out.append("|---|---|---|")
    for r in checks:
        out.append(f"| {r['status']} | {r['name']} | {r['detail'][:220]} |")
    out.append("")
    kinds = Counter((e.layer, e.kind) for e in graph.edges)
    out.append("## Edge kinds")
    out.append("")
    out.append("| kind | meaning | count |")
    out.append("|---|---|---|")
    for (layer, kind), n in sorted(kinds.items()):
        out.append(f"| `{kind}` ({layer}) | {KINDS[kind]} | {n} |")
    out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------
# baseline comparison (semantic diff)
# --------------------------------------------------------------------------

def compare_edges(new: List[Edge], old: List[Edge]) -> Dict[str, Any]:
    new_keys = {e.key(): e.edge_id for e in new}
    old_keys = {e.key(): e.edge_id for e in old}
    only_new = sorted(set(new_keys) - set(old_keys))
    only_old = sorted(set(old_keys) - set(new_keys))
    return {
        "new_total": len(new),
        "old_total": len(old),
        "only_in_new": [{"key": list(k), "edge_id": new_keys[k]} for k in only_new],
        "only_in_old": [{"key": list(k), "edge_id": old_keys[k]} for k in only_old],
    }
